version: "3"


services:

  mailserver:
    image: analogic/poste.io
    container_name: mailserver-posteio
    restart: always
    network_mode: "host"
    expose:
      - "25"
      - "8080"
      - "4443"
      - "110"
      - "143"
      - "465"
      - "587"
      - "993"
      - "995"
    volumes:
      - /home/workspace-docker/poste-docker/mailserver-data/:/data

    environment:
      - TZ=Europe/Madrid
      - h=email.grafispapeleriacopisteria.ga
      - HTTP_PORT=8080
      - HTTPS_PORT=4443
      - DISABLE_CLAMAV=TRUE