version: "3"


services:

  mailserver:
    image: analogic/poste.io
    container_name: mailserver-posteio
    restart: always
    network_mode: "host"
    
    volumes:
      - /home/workspace-docker/poste-docker/mailserver-data/:/data

    environment:
      - HTTPS=ON